theme = "native"
icons = "awesome"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui-connect"
ap_format = "{ssid}"
device_format = "{icon}{ap}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d %M %R"
on_click = "gnome-clocks"
